In [2]:
import numpy as np
import pandas as pd
import tqdm

In [4]:
dfs = []
with tqdm.tqdm(total=10) as pbar:
    for i in range(10):
        dfs.append(pd.read_parquet(f"part-0000{i}.parquet"))
        pbar.update(1)
df = pd.concat(dfs, axis=0)
df

100%|██████████| 10/10 [00:46<00:00,  4.68s/it]

,timestamp,application_id,client,session_id,event_type,event_category,event_name,event_label,device_screen_name,timezone,device_is_webview,page_urlhost,page_urlpath_full,net_connection_type,net_connection_tech
0,2020-01-15 08:46:32.579,anketa,107efb4507525ce982e19331b36b0e2f,9a1366886da59ec85f0ef5e06f1e97f6,pv,None,None,None,None,Asia/Omsk,True,anketa.alfabank.ru,03eb3ceab6204f8b602f1863f7fbce01,None,None
1,2020-04-29 19:20:09.705,anketa,32dac9ab28a497a8061e02786bb3a95a,bdf7fc21e4e88d1b4f0838c80b21a1e3,pv,None,None,None,None,Asia/Yekaterinburg,True,anketa.alfabank.ru,03eb3ceab6204f8b602f1863f7fbce01,None,None
2,2020-02-21 03:21:24.058,anketa,489818f57087b59790435b3acf18018a,8bae6c4249db74dc0937e1ff00d61079,pv,None,None,None,None,Asia/Yakutsk,True,anketa.alfabank.ru,03eb3ceab6204f8b602f1863f7fbce01,None,None
3,2020-08-06 06:54:30.918,anketa,489818f57087b59790435b3acf18018a,3a95ba68795b745ca09ebee138b418ef,pv,None,None,None,None,Asia/Yakutsk,True,anketa.alfabank.ru,03eb3ceab6204f8b602f1863f7fbce01,None,None
4,2020-02-28 18:51:56.452,anketa,6dde48ffeb6d354628303c9d9b6721be,1db024ef087161f30a3c981cb32bb565,pv,None,None,None,None,Asia/Omsk,True,anketa.alfabank.ru,03eb3ceab6204f8b602f1863f7fbce01,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11811776,2020-01-30 06:08:58.984,site,1f89fcbd636baf8b4a08f003626c1c07,fe232104d6c408463b4d1588137af8bb,se,flocktory-precheckout,system-show,e1da19a13dedeb0c5c02ef0750201fe0,None,Europe/Minsk,True,travel.alfabank.ru,d612076c3948baf3fc5cb65ccd006db5,None,None
11811777,2020-03-10 16:15:16.416,site,bd5979fffbf9d2e3d66203474df97898,2045bacc141fb1786f25a192dbab8264,se,Pixel,Match,a19e4a8f8af8d3326120cd5a2b946ee9,None,Europe/Minsk,True,travel.alfabank.ru,e4286cb4e67fcfd64f41b982bc3dbb8a,None,None
11811778,2020-01-04 13:49:12.932,site,8ebd42b552e51e1e2dfb2ebea56d16f7,29ec828dbf2d8fb6c2fd0b737169ef9b,se,Pixel,Match,a19e4a8f8af8d3326120cd5a2b946ee9,None,Europe/Minsk,True,travel.alfabank.ru,e98a4d4a15356368e51de30169a611a8,None,None
11811779,2020-06-03 11:26:29.646,site,f73c439a6b0cfe941fcbefa8a1d94610,d33008b1774c8980641c369ac69d4639,se,JivoSite,Offline message sent,1a70145c185f60da9db8d0e9755183b4,None,Asia/Karachi,True,travel.alfabank.ru,ea4353a6cbbd67ac59323abfa7a3071b,None,None
11811780,2020-02-25 14:44:42.995,site,7f82e274bc45c146adfe2dae7505360c,cd19cc24771c17df183579f5726c58d1,se,Pixel,Match,a19e4a8f8af8d3326120cd5a2b946ee9,None,Asia/Omsk,True,travel.alfabank.ru,f569938d65941793a7e8c1077bd7259e,None,None

In [14]:
train = pd.read_csv("alfabattle2_abattle_train_target.csv", index_col="client_pin")
train

,session_id,timestamp,multi_class_target
client_pin,,,
7cf9221322a0e2fdefb1b998b8f2ab29,0000029e72e5fcde6a9f29c3a3ed198f,2020-06-15 14:01:12,main_screen
5f16c0ab27a806fd08db3122921adf3a,00063dffa47b0fe5556b2b9e8beddb6a,2020-03-21 12:59:34,invest
ec868fc2b388293cf10e18ee9518d72f,0007857f36d268ec46fcb7305538a1c7,2020-01-24 18:18:55,statement
91f55a33d7502c1a1fa5da7ff2f7b648,000a7f25fc3609cdfda54c5f059aab00,2020-03-15 19:50:23,main_screen
3ef1020bda95ce7836d2680fa553ecb7,000b746d6616669663feaa1474ac97f1,2020-02-20 07:56:58,main_screen
...,...,...,...
8f1fc0c1216403afc07b5d602680b313,ffebe10d7dc64cf5afac5928a8174195,2020-06-16 15:21:00,main_screen
2675ab80450c36c8f2600d8dcd60b43c,fff0805a552d3df84312dbe626702335,2020-04-22 20:31:09,main_screen
2c5e889f5360eabefc21181240d0d38e,fff1dd487c78ba63c1aa71460656430c,2020-06-02 11:43:06,main_screen
eb90469b91e22f5ba12986acd873def9,fff8f2129c14f157241c08c63c506180,2020-03-30 00:39:03,main_screen
73b4ee58ec16778d9e966bdc0595fcb7,fffed0d3e5a8aa83b17ea4f1aed68b6f,2020-06-20 17:35:50,chat

In [15]:
pred = pd.read_csv("alfabattle2_abattle_sample_prediction.csv", index_col="client_pin")
pred_time = pd.read_csv("alfabattle2_prediction_session_timestamp.csv", index_col="client_pin")
pred = pred.join(pred_time)
pred

                                          prediction            timestamp
client_pin
f0c674b2bb4dc64be607029271d706ec         credit_info  2020-08-01 00:00:53
90725b54ce77576883813d87749df6bd         credit_info  2020-08-01 00:02:57
eb0f82d74c7b7bd5eafbd5b5f8cb3e2a        own_transfer  2020-08-01 00:03:14
831bf4c0ecccc55e536b8cfb9153d672           statement  2020-08-01 00:04:44
3f1a5a1c492ce877af833113e59c5797              invest  2020-08-01 00:06:40
...                                              ...                  ...
4e46e206d38dcb7af41d9ced20d50ac2         main_screen  2020-09-30 23:41:47
5b59bf5bd1e07775b1bc95dd7151d2cd       card_recharge  2020-09-30 23:43:25
94bcc852dd7f806f6c733056d1b0be7b  card2card_transfer  2020-09-30 23:50:37
2061f779928217eea2878fd3b605fafd  card2card_transfer  2020-09-30 23:53:03
e2f0cede9e3bc3d6ed7c77c4e08af136     mobile_recharge  2020-09-30 23:58:32

[79268 rows x 2 columns]